### ISSUE TITLE
CSS

### ISSUE THREAD

**Issue by jacknoble** [rorysaur/quack#12]
Make it not look like shit

**Comment by jacknoble** [comment]
Any thoughts on a css framework?

**Comment by rorysaur** [comment]
i had my eye on bootflat or flat-ui (haven't figured out what the difference is tbh).. basically, i like bootstrap purely for the grid system. hate the aesthetics and hate all their widgets and the js api.

**Comment by rorysaur** [comment]
i can be talked out of bootstrap if there's something with a good grid system..

**Comment by satishkunisi** [comment]
Consider Foundation. You don't get any styles out of the box but that seems
fine considering all the UI minds around here.

On Tuesday, March 17, 2015, Rory Ou notifications@github.com wrote:

> i can be talked out of bootstrap if there's something with a good grid
> system..
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/rorysaur/quack/issues/12#issuecomment-82757228.

## 

Sent from Gmail Mobile

**Comment by rorysaur** [comment]
let's explore some more and maybe use a minimal library(ies).. like one that is just a grid system!

**Comment by jacknoble** [comment]
http://www.hongkiat.com/blog/bootstrap-alternatives has good options. Foundation seems ... intent on selling me courses or premium video tutorials. But maybe I just can find the good free stuff.

**Comment by jacknoble** [comment]
I like how flat-ui looks. The the hover transition is too slow but I'm sure that can be fixed. http://thisisdallas.github.io/Simple-Grid/ looks nice as far as bare bones stuff goes. More fun to customize the look of things without worrying about media queries much.

**Comment by jacknoble** [comment]
Susy --- http://susydocs.oddbird.net/en/latest/# is intriguing

**Comment by jacknoble** [comment]
Working on this now. I have the sassify transform working and I'm adding http://neat.bourbon.io/examples/ as our grid framework.

**Comment by rorysaur** [comment]
now that it looks better than shit, let's close this ticket in favor of specific styling tasks.
