### ISSUE TITLE
We're going to want multiple channels

### ISSUE THREAD

**Issue by jacknoble** [rorysaur/quack#13]
and an interface to handle them. I'm thinking some combination of tabs and tiling windows. :join channel_name should join/create a new channel and :leave should close the tab/window.

**Comment by rorysaur** [comment]
i think we should do a modified version of what Slack does.. have a channels list sidebar on the left, divided into channels you're in, and channels you're not in (make an issue for this). agree with you about the behavior of join/leave commands (each command is an issue). clicking on a channel name should change the ChannelMessages component to that channel (another issue). eventually we can have keyboard shortcuts for flipping through them (moar issues!).

**Comment by rorysaur** [comment]
we should use react-router for channels, just for funsies.

**Comment by rorysaur** [comment]
see #14 for a sample schema of how we want to store channels.. when a user creates a channel, it should push a username value (string) into the firebase path `firebaseRef/channels/<channel name>/users`.. i think that if you haven't used that path before, firebase will just make it for you

**Comment by jacknoble** [comment]
https://github.com/rorysaur/quack/pull/65

**Comment by jacknoble** [comment]
Resolved!
