### ISSUE TITLE
research webpack instead of "-ify" libraries

### ISSUE THREAD

**Issue by rorysaur** [rorysaur/quack#20]

**Comment by jacknoble** [comment]
Whats this?

**Comment by rorysaur** [comment]
the build process.. transpiling JSX to JS, concatenating, etc. currently we're using reactify, browserify and watchify. webpack is the newer, super trendy thing that's supposed to take care of all those steps.. it might be good to get used to it in case it becomes the industry standard and browserify becomes deprecated/obsolete.

**Comment by jacknoble** [comment]
Anywhere I can read up about our build process? Can we add a sass transpiler + css concatenation?

**Comment by rorysaur** [comment]
the whole thing is pretty much outlined in the readme, and then you can look at the individual libraries' readmes. it's very minimal. nothing is set up for CSS so we can add whatever.

**Comment by rorysaur** [comment]
oh, guess i didn't actually write out what each library does. reactify: JSX to JS. browserify: concatenates everything into `bundle.js`. watchify: re-runs the other two whenever a file is changed.

**Comment by jacknoble** [comment]
We're using web pack now!
