### ISSUE TITLE
We want a channels side bar

### ISSUE THREAD

**Issue by jacknoble** [rorysaur/quack#25]

**Comment by jacknoble** [comment]
per https://github.com/rorysaur/quack/issues/13 "have a channels list sidebar on the left, divided into channels you're in, and channels you're not in"

**Comment by benjaminkreen** [comment]
I'm going on unassign myself from these until I wrap up the autoscroll code.

**Comment by jacknoble** [comment]
https://github.com/rorysaur/quack/pull/65

**Comment by jacknoble** [comment]
Resolved!
