### ISSUE TITLE
Messages are going to need to scroll

### ISSUE THREAD

**Issue by jacknoble** [rorysaur/quack#33]
The chat window needs to be a set size and old messages need to disappear as they are replaced by new ones. Instead of getting all the messages from the message store maybe it could just get the last few? But it seems like the actual measure is lines of text, not message count.

**Comment by rorysaur** [comment]
yeah, i was going to add this too! maybe (if it's not too difficult) we can just set the height to the window height, load all messages, and keep it always scrolled to the bottom?

**Comment by rorysaur** [comment]
and later we can do infinite scroll.. or just delete old messages :smiling_imp:

**Comment by jacknoble** [comment]
So some of this is in my working branch. It's not perfect but I think we can close for now unless @benjaminkreen wants to jump back in.
