### ISSUE TITLE
POLL: Default Command Character

### ISSUE THREAD

**Issue by jacknoble** [rorysaur/quack#51]
So right now you start command messages (like changing your nick, editing the last message, eventually leaving, joining, switching tabs, #nomice) with `:`. 

We're going to enable escaping the command character with `\` and changing your command character is already possible. But there is still the question of what the default should be.

Options:
(1) `:` - Colon. The current command character. Advantages: just like vim. Disadvantages: have to escape for some emoticons.
(2) `/` Forward-slash. Advantages: like most irc clients and other chat apps. Disadvantages: /s/spll/spell is sort of funny. Vim flow.
(3) - Other. What else would be good?

**Comment by rorysaur** [comment]
`/`

:smile:

**Comment by satishkunisi** [comment]
/

**Comment by gotno** [comment]
`/`

side note: `/` isn't necessarily always used for regular expression substitution. most engines implement it in such a way that you can use any matching characters, provided you escape those characters if you use them in the regex. ex: `s:foo:bar` or `s|foo|bar`

**Comment by djwy** [comment]
\

**Comment by Supernats** [comment]
`/` is the way of IRC. Anything else would be irksome.

**Comment by jacknoble** [comment]
@gotno thats a good point but it's more having the habit translate over thats the issue for me. Same with `/query` for search.

Rory and I had a discussion today about making quack genuinely modal. You would have a chat mode which would have commands that start with `/` and involve doing things other people see in chat-- editing messages, changing your nick, `/shrug`ging etc. And a separate mode for utility operations that only affect the user-- searching old chats, changing settings, splitting panes etc. `:` In the second mode (utility mode?) you can't event send messages at all just like you enter insert mode before adding text to a file in vim.

Anyway, clearly everyone but me likes `/` (also I'm not overly partial to either) so lets change it.
